#!/usr/bin/env python2

import gflags as flags
import subprocess
import sys
import os

FLAGS = flags.FLAGS

def setgflags():
    flags.DEFINE_integer('b', 100, "set beam size, (DEFAULT=100)")
    flags.DEFINE_boolean('verbose', False, "print out runtime in seconds, (DEFAULT=FALSE)")
    argv = FLAGS(sys.argv)

def main():
    beamsize = str(FLAGS.b)
    is_verbose = '1' if FLAGS.verbose else '0'

    path = os.path.dirname(os.path.abspath(__file__))
    cmd = ["%s/%s" % (path, ('bin/linearalifold')), beamsize, is_verbose]
    subprocess.call(cmd, stdin=sys.stdin)
    
if __name__ == '__main__':
    setgflags()
    main()

